# Travis Continuous Integration Configuration File, based on ..
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro ROSWS=wstool BUILDER=catkin
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-rosinstall ros-$ROS_DISTRO-catkin
  # MongoDB hack - I don't fully understand this but its for moveit_warehouse
  - sudo apt-get remove -y mongodb mongodb-10gen
  - sudo apt-get install -y mongodb-clients mongodb-server -o Dpkg::Options::="--force-confdef" # default actions
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
install: # Use this to install any prerequisites or dependencies necessary to run your build
  # Create workspace
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME/src
  - cd ~/ros/ws_$REPOSITORY_NAME
  - $ROSWS init src
  - $ROSWS set gazebo_models --hg https://bitbucket.org/k-okada/gazebo_models --version add_apollo_15_landing_site -t src 
  - $ROSWS update -j10 -t src
  - ln -s $CI_SOURCE_PATH src/$REPOSITORY_NAME # Link the repo we are testing to the new workspace
  # Install dependencies for source repos
  - rosdep install -r -n --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - cd ~/ros/ws_$REPOSITORY_NAME
  - catkin_make -j4
  - catkin_make test
  - catkin_make run_tests
  - catkin_make install
  - source install/setup.bash
  - roslaunch --nodes tetris_description rviz.launch
  - GAZEBO_MODEL_PATH=~/ros/ws_$REPOSITORY_NAME/src/gazebo_models roslaunch --nodes tetris_launch demo.launch
after_failure:
  - find ${HOME}/.ros/test_results -type f -exec echo "== {} ==" \; -exec cat {} \;
  - for file in ${HOME}/.ros/log/rostest-*; do echo "=== $file ==="; cat $file; done